# Generated by Django 4.0 on 2022-02-04 14:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='module/vidoes')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
