# Generated by Django 4.0 on 2022-02-04 14:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_module_status_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='module/vidoes')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='module',
            old_name='them',
            new_name='module_name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='text',
        ),
        migrations.RemoveField(
            model_name='module',
            name='video',
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(related_name='lessons', to='accounts.Lessons'),
        ),
    ]
