# Generated by Django 4.0 on 2022-02-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lessons_rename_them_module_module_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='lessons',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
