# Generated by Django 4.0 on 2022-02-07 10:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_module_lessons_delete_courses_delete_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
                ('video', models.FileField(upload_to='module/vidoes')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.BooleanField(default=True)),
                ('lesson_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_mentor', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('lessons', models.ManyToManyField(related_name='lessons', to='courses.Lessons')),
                ('module_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_mentor', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_avatar', models.ImageField(blank=True, upload_to='courses/avatar')),
                ('course_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('course_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mentor', to='accounts.customuser')),
                ('modules', models.ManyToManyField(related_name='modules', to='courses.Module')),
            ],
        ),
    ]
